name: Build

on:
  push:
    branches: [ "main", "private-*" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Checkout BoringSSL (submodule)
      run: git submodule update --init --depth=1 bssl-compat/boringssl

    - name: Remove packages
      run: sudo apt autoremove --purge -y clang-10 clang-12

    - name: Install packages
      run: sudo apt install -y libclang-cpp11-dev libclang-11-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/bssl-compat -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
